import { Providers } from "./providers";
import { Climate_Crisis, Gabarito, Oswald, DynaPuff, Signika, Merienda } from 'next/font/google'
import "./globals.css";
import ReCaptchaV3Button from "./components/rendeReCaptchaV3/ReCaptchaV3Button";

const climate = Climate_Crisis({
  subsets: ['latin'],
  variable: '--font-climate',
  display: 'swap',
})

const gabarito = Gabarito({
  subsets: ['latin'],
  variable: '--font-gabarito',
  display: 'swap',
})

const oswald = Oswald({
  subsets: ['latin'],
  variable: '--font-oswald',
  display: 'swap',
})

const dynaPuff = DynaPuff({
  subsets: ['latin'],
  variable: '--font-dynaPuff',
  display: 'swap',
})

const signika = Signika({
  subsets: ['latin'],
  variable: '--font-signika',
  display: 'swap',
})

const merienda = Merienda({
  subsets: ['latin'],
  variable: '--font-merienda',
  display: 'swap',
})


export const metadata = {
  title: "Fight Stock, o poder está nas suas mãos!",
  description: "Generated by create next app",
  charset: 'utf-8',
  viewport: 'width=device-width, initial-scale=1',
  keywords: 'Vendas, artes marciais, produtos, ferramentas',
  author: 'TechLivity',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="w-full h-[100vh] dark">
      <head>
        <meta name="description" content={metadata.description} />
        <meta name="keywords" content={metadata.keywords} />
        <meta name="author" content={metadata.author} />
        <title>{metadata.title}</title>
      </head>
      <body className={`${climate.variable} ${gabarito.variable} ${oswald.variable} ${dynaPuff.variable} ${signika.variable} ${merienda.variable} `}>
        <Providers>
          <ReCaptchaV3Button></ReCaptchaV3Button>
          {children}
        </Providers>
      </body>
    </html>
  );
}
