import { Providers } from "./providers";
import { Climate_Crisis, Gabarito, Oswald, DynaPuff, Signika, Merienda } from 'next/font/google'
import "./globals.css";

const climate = Climate_Crisis({
  subsets: ['latin'],
  variable: '--font-climate',
  display: 'swap',
})
 
const gabarito = Gabarito({
  subsets: ['latin'],
  variable: '--font-gabarito',
  display: 'swap',
})

const oswald = Oswald({
  subsets: ['latin'],
  variable: '--font-oswald',
  display: 'swap',
})
 
const dynaPuff = DynaPuff({
  subsets: ['latin'],
  variable: '--font-dynaPuff',
  display: 'swap',
})

const signika = Signika({
  subsets: ['latin'],
  variable: '--font-signika',
  display: 'swap',
})

const merienda = Merienda({
  subsets: ['latin'],
  variable: '--font-merienda',
  display: 'swap',
})


export const metadata = {
  title: "Fight Stock, o poder está nas suas mãos!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="w-full h-[100vh] dark">

      <body className={`${climate.variable} ${gabarito.variable} ${oswald.variable} ${dynaPuff.variable} ${signika.variable} ${merienda.variable} `}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
